include: package:flutter_lints/flutter.yaml
# Note: This will resolve after running 'flutter pub get'

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_print: false
    prefer_single_quotes: true
    sort_child_properties_last: true
